### ISSUE TITLE
SLU3 validates output type

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/bootcamp#52]
If you are returning a pandas.Series you answer might be actually correct but will not pass the tests.
Please reformulate the answer to return a pandas.Dataframe.

**Comment by PedroGFonseca** [comment]
@hcastilho which exercise is this for?

**Comment by hcastilho** [comment]
All exercises that state in the function definition that they expect a pandas Dataframe.
Like so:
```
    Returns:
       df (pd.DataFrame): transformed DataFrame
```

**Comment by echo66** [comment]
This issue is related to a concept called "natural order". In simple terms, it means that "list" (e.g. python list, pandas dataframe, ordered iterables, pandas series, etc) elements having the same sorting value (i.e. ties) will preserve the same list order that they had in the original list. In order to understand what I'm saying, let's look at the following example

Original list
```
id, val
1, 30
2, 11
3, 10
4, 91
5, 91
6, 91
7, 91
8, 32
9, 91
```

A sorting algorithm that preserves the natural order of elements will produce:
```
id, val
3, 10
2, 11
1, 30
8, 32
4, 91
5, 91
6, 91
7, 91
9, 91
```

On the other hand, a sorting algorithm that doesn't preserve natural order could have the following result
```
id, val
3, 10
2, 11
1, 30
8, 32
4, 91
7, 91
9, 91
5, 91
6, 91
```

When you read "stable" at [numpy sort docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.sort.html), they are talking about the natural order.

**Comment by PedroGFonseca** [comment]
The docstring clearly states the expected return type. To avoid complexity will leave the requirement for a DataFrame output.

**Comment by PedroGFonseca** [comment]
(Leaving open so that students can see clarification)
